### ISSUE TITLE
Missing goimage and gopaypal

### ISSUE THREAD

**Issue by forgee** [Raggaer/castro#107]
It seems that [github.com/raggaer/goimage](https://github.com/raggaer/goimage) and [github.com/raggaer/gopaypal](https://github.com/raggaer/gopaypal) have disappeared (or possibly become private), making it impossible to compile castro.

@Raggaer do you know what happened?

**Comment by joseluis2g** [comment]
he removed them while cleaning github, I just cloned them, change raggaer to joseluis2g

**Comment by Raggaer** [comment]
Yes sadly they were removed... It may be good to also change it on the repository, honestly this repo is pretty much dead. I was thinking on making it archived and move on.
