### ISSUE TITLE
New premium time handling in TFS

### ISSUE THREAD

**Issue by forgee** [Raggaer/castro#109]
TFS has changed how they handle premium time and now just use a timestamp in `premium_ends_at` instead of `premdays` and `lastday` in the database.
See this PR: https://github.com/otland/forgottenserver/pull/2813

I think it is too much work to keep compatibility with both old and new TFS, so I suggest we create a separate branch or tag a release for older TFS and let master keep compatibility with latest TFS.
Are there any other suggestions or opinions before I start working on this?

**Comment by Raggaer** [comment]
I would just go and update the current code, supporting only newest TFS. But I dont mind having another branch, up to you =)

Thanks

**Comment by forgee** [comment]
This should be fixed with 8efd60aeff1dbdc391f0f82de83e1a17c4a0977b. Please report any issues.

I decided to just update the master branch because TFS 1.3 has been going for so long and I don't know if castro still worked with the actual TFS 1.2 release anyway.
