### ISSUE TITLE
Redirect loop when no articles in database

### ISSUE THREAD

**Issue by forgee** [Raggaer/castro#29]
If there are no articles in the database this results in a redirect loop (ERR_TOO_MANY_REDIRECTS).
https://github.com/Raggaer/castro/blob/master/pages/index/get.lua#L20-L23

One solution could be to insert a dummy article and continue to render the page:
```lua
if data.articles == nil then
   data.articles = {{title = "No articles", text = "No articles exist yet.", created_at = 0}}
end
```
![alt text](http://i.imgur.com/5jZe3lu.png)

**Comment by Raggaer** [comment]
I will check when back from work. Feel free to do a pull request if you wish.

Did you try last commit? Thanks

**Comment by Raggaer** [comment]
Last commit should have this fixed

**Comment by forgee** [comment]
I'm a commit behind, will try the last one but it looks like you fixed it.

**Comment by forgee** [comment]
I have confirmed that it works as expected as of https://github.com/Raggaer/castro/commit/baf51bee07b3841723a9c8dc626cceecb92bb01e.
