### ISSUE TITLE
JSON marshalling from Lua

### ISSUE THREAD

**Issue by forgee** [Raggaer/castro#42]
I still have the same problem with `json:marshal(table)` turning "arrays" into objects and I'm pretty sure I found the reason for that.
In `func TableToMap(table *lua.LTable)` the index is always set as a string [here](https://github.com/Raggaer/castro/blob/master/app/lua/util.go#L104).
The result is that `table[1]` becomes equivalent to `table["1"]`.

**Comment by Raggaer** [comment]
You can still range over them I guess? This needs big changes to make it work

**Comment by Raggaer** [comment]
Latest commit maybe fixes this. Waiting for your answer.

`queryResults` is no longer needed on templates with these changes

**Comment by forgee** [comment]
Yes, they work the same as any "object". There are 2 workarounds that I can think of off the top of my head. Either range over them and recreate the arrays in JavaScript, or use a Lua based function.

With the latest commit I get this error:
`Cannot marshal the given table: json: unsupported type: map[interface {}]interface {}`
Code used:
```lua
local chart = {
    labels = {"A", "B", "C"},
    datasets = {
        {
            label = 'Players online',
            data = {1, 2, 3},
            backgroundColor = 'rgba(0, 140, 186, 0.2)',
            borderColor = 'rgba(0, 140, 186, 1)',
            borderWidth = 1,
        }
    }
}
print(json:marshal(chart))
```

I am not sure if it conforms 100% to the JSON standard but the Lua function I wrote has worked perfectly for everything I have tried so far. I added a wrapper for json:marshal, so we could possibly use it as a temporary fix and use json:marshal in any script that needs it and easily remove the Lua implementation later, without the need to rewrite scripts.
Feel free to use it if you want: https://gist.github.com/forgee/6521bf1b84295f5273b7e3514cc748a0

**Comment by Raggaer** [comment]
The error might be because when you create an array the map is no longer using key strings but integers...
There is no solution I can think off now except range over them with the result beeing `table["1"]`...

```lua
    local chart = {
        labels = {"A", "B", "C"},
        datasets = {
            ["1"] = {
                
            }
        }
    }
```
That could work too on the Go part. not sure about the javascript part. Of course we can use a lua script to do the work

**Comment by Raggaer** [comment]
Hope this new commit fixes all the problems

**Comment by forgee** [comment]
Things are looking good. :thumbsup:

**Comment by Raggaer** [comment]
I guess this can be closed now. If anything new comes up feel free to re-open the issue
