### ISSUE TITLE
Expected behavior of cache:get()

### ISSUE THREAD

**Issue by forgee** [Raggaer/castro#44]
Using cache:get("test") without having first set a value on the key results in a script breaking error (L.ArgError).
I would expect the call to cache:get() to return nil if the key is not set.

Example snippet:
```lua
function get()
	local cached = cache:get("test")
	if cached == nil then
		cache:set("test", "SomeData", "4h")
	end
end
```
Currently the above snippet results in an error like this : `.../get.lua:2: bad argument #1 to get (No cache value found using the given key)` unless "test" is already set.

Replacing [this line](https://github.com/Raggaer/castro/blob/master/app/lua/cache.go#L36) with `L.Push(lua.LNil)` yields the behavior I would expect.

Is there a reason for the current behavior that I am missing?

**Comment by Raggaer** [comment]
Your issue should be the default behaviour. I will commit this soon or feel free to open a PR

**Comment by forgee** [comment]
Thanks for the quick response. Might as well let you do it since you will probably be faster than me either way.
