### ISSUE TITLE
 how to install?

### ISSUE THREAD

**Issue by ninja9158** [Raggaer/castro#52]
config.lua  How to configure?
Thank you!

**Comment by Raggaer** [comment]
You need to setup your  `config.lua` as you would normally do. Grab a compiled version of the AAC with the required folders.

When you first start the AAC the installation process will start

**Comment by ninja9158** [comment]
I will not generate this document?

`local mysqlUser = "root"
local mysqlPass = "root"
local mysqlDatabase = "castro"
`

I am writing incorrectly here?

**Comment by Raggaer** [comment]
It reads your server `config.lua` so just edit the database settings as you would normally and start the AAC executable

**Comment by ninja9158** [comment]
Do not understand? My environment is windows, after the prompt suggested config.lua file does not exist。
How do i create this file? 

I'm sorry, my English is not good

**Comment by Raggaer** [comment]
Prompt asks for your server path. Example `C:\Server\` the file `config.lua` MUST exists... I am lost `config.lua` is needed for your server not for the AAC. Castro uses `config.toml` 

Are you entering a good path in your installation process?

**Comment by ninja9158** [comment]
Does config.lua not be created automatically?   

Castro is not installed. Running installation process
Insert your server location: d:\castro
2017/04/11 21:01:08 open d:\castro\config.lua: The system cannot find the file specified.

**Comment by Raggaer** [comment]
You need to enter your `TFS` location not AAC location

**Comment by ninja9158** [comment]
Ok, thank you
