### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Raggaer** [Raggaer/castro#55]
We are almost near release. But before that I need to test the AAC against a heavy populated database

**Comment by joseluis2g** [comment]
We are currently using znote as db but you can remove all the things that you dont want and test with it, got lot of players and accounts created.

**Comment by Raggaer** [comment]
If you dont mind exporting some of your database tables. All players and guild related tables. Accounts are not neccesary since that may expose personal information.

**Comment by joseluis2g** [comment]
Lemme talk with my team so :)

**Comment by Raggaer** [comment]
Any news @joseluis2g ?
