### ISSUE TITLE
Extension verification

### ISSUE THREAD

**Issue by Raggaer** [Raggaer/castro#68]
Verify extensions before installing
Maybe hash check?

**Comment by gpedro** [comment]
md5sum and sha1sum verification can solve that problem

**Comment by Raggaer** [comment]
The tricky part is how to add the hash to the plugin, maybe inside the plugin json file but that requires users to manually introducing the hash

**Comment by Raggaer** [comment]
There is no need to verify, the forum where the extension is uploaded (or the plugin list) should do this
