### ISSUE TITLE
Add i18n

### ISSUE THREAD

**Issue by Raggaer** [Raggaer/castro#87]

**Comment by joseluis2g** [comment]
Nice  :heart_eyes:

**Comment by Raggaer** [comment]
Added to main branch, will keep this open incase any issue appears

**Comment by joseluis2g** [comment]
I got a question.
How do I create a language switcher?

**Comment by Raggaer** [comment]
I forgot to add the default language array, `i18n.Language` is a lua table with all languages the user accepts...

You can use a widget and using a session or an http cookie to save the language the user selects (on a widget or on the header using a ajax request to a page)

**Comment by joseluis2g** [comment]
Can you make an example? I think I do not understand it at all but I will do my tests for sure.

**Comment by Raggaer** [comment]
On your templates you call something like

`{{ i18n .session.lang "index" }}` to display content

On the first request `.session.lang` will be empty, if its empty the `default.i18n` language file will be used.

To switch languages you can make a lua page that calls `session.set("lang", "LANGUAGE")` to update the laanguage the user wants to use

**Comment by joseluis2g** [comment]
Got it
