### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by goadv** [Raggaer/castro#89]
`go build`
output:
`./main.go:81:18: cannot use PageNotFound (type func(http.ResponseWriter, *http.Request)) as type http.Handler in assignment:
	func(http.ResponseWriter, *http.Request) does not implement http.Handler (missing ServeHTTP method)`

[main.go#L81](https://github.com/Raggaer/castro/blob/71e3d1599cef4a68c37b97c97ec4befb8db36815/main.go#L81)
`router.NotFound = PageNotFound`
**replace**
`router.NotFound = http.HandlerFunc(PageNotFound)`

**Comment by Raggaer** [comment]
Did you build using dep? since appveyor build passes

**Comment by goadv** [comment]
No, I do not using dep, all packages have the last state with github.com.

**Comment by Raggaer** [comment]
That may be the problem, I recommend u to use dep, I will however push a commit that fixes this

Thanks
