### ISSUE TITLE
Implementing Bug Tracker?

### ISSUE THREAD

**Issue by iTinkz** [Raggaer/castro#90]
This is just a suggestion that might be appreciated of many people and even give an feature that many of the other AAC doesn't have.

My suggestion is to implement a [Bug Tracker] or [Report Bug] section inside a player account where a person can choose which bug to report Map/Spell/Quest etc.. With colours if possible. 

An admin account would be able to see "notifications" of an added bug. He should be able to respond / close the report when issue is fixed, perhaps even give "points" to the players account that reported.

Maybe have a section bug reports so that all people can see fixed bugs / not fixed bugs yet?

An example of a such thing is githubs Issue section where labels can be added etc..

**Comment by Raggaer** [comment]
I dont think this should be into the core repo as it seems more to be a plugin or something else done in lua

**Comment by joseluis2g** [comment]
I do not think this is really important but a personal feature for some ots. 
Have anyone tested this? Is something important missing?

**Comment by Raggaer** [comment]
@joseluis2g What do you mean by testing this? This is not into the core

**Comment by joseluis2g** [comment]
I mean Castro itself. Taking your second statement; "easy to do via Lua"
