### ISSUE TITLE
Refreshing Online List

### ISSUE THREAD

**Issue by iTinkz** [Raggaer/castro#94]
Even though a player logouts from the server it still shows that he is still online on the page who is online. I've checked the player_online table and it works correctly. 

I noticed if I login on player name "Test" logout it says on website "Test" is online. But when I login on "Test2" and logout it now ways Test2 is online. "Test" is does no longer show as online, but instead "Test2"

I've also set the cache to
[Cache]
  Default = "5m"
  Purge = "1m"

**Comment by Raggaer** [comment]
This issue was tested (with MiterTinkz) and everything worked fine.
